// zeppelin-web-angular/projects/zeppelin-react/src/components/visualizations/TableVisualization.tsx
/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { useState, useEffect, useMemo, useRef } from 'react';
import { Table } from 'antd';
import { Column, Line, Pie, Scatter } from '@antv/g2plot';
import { VisualizationControls } from './VisualizationControls';
import { parseTableData, exportFile } from '@/utils';
import type { ParagraphConfigResult, ParagraphIResultsMsgItem, VisualizationMode } from '@zeppelin/sdk';

interface TableVisualizationProps {
  result: ParagraphIResultsMsgItem;
  config?: ParagraphConfigResult;
}

export const TableVisualization = ({ result, config }: TableVisualizationProps) => {
  const [currentMode, setCurrentMode] = useState<VisualizationMode>(config?.graph.mode || 'table');
  const chartRef = useRef<HTMLDivElement>(null);

  const tableData = useMemo(() => parseTableData(result.data), [result.data]);

  const handleExport = (type: 'csv' | 'xlsx') => {
    if (tableData) {
      exportFile(tableData, type);
    }
  };

  const renderVisualization = () => {
    if (!tableData || tableData.rows.length === 0) return null;

    if (currentMode === 'table') {
      const columns = tableData.columnNames.map((col, idx) => ({
        title: col,
        dataIndex: idx,
        key: idx,
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        render: (text: any) => text
      }));

      const dataSource = tableData.rows.map((row, idx) => ({
        key: idx,
        ...row.reduce((acc, cell, cellIdx) => ({ ...acc, [cellIdx]: cell }), {})
      }));

      return (
        <Table
          columns={columns}
          dataSource={dataSource}
          size="small"
          scroll={{ x: true }}
          pagination={{ pageSize: 50 }}
        />
      );
    }

    return <div ref={chartRef} style={{ height: 400 }}></div>;
  };

  useEffect(() => {
    if (!chartRef.current || !tableData || tableData.rows.length === 0 || currentMode === 'table') return;

    const data = tableData.rows.map((row, idx) => ({
      category: row[0] || `Row ${idx + 1}`,
      value: parseFloat(row[1] || '0') || 0,
      x: idx,
      y: parseFloat(row[1] || '0') || 0
    }));

    let chart: Column | Line | Pie | Scatter | null = null;

    switch (currentMode) {
      case 'multiBarChart':
        chart = new Column(chartRef.current, {
          data,
          xField: 'category',
          yField: 'value',
          color: '#1890ff',
          columnWidthRatio: 0.8
        });
        break;
      case 'lineChart':
        chart = new Line(chartRef.current, {
          data,
          xField: 'category',
          yField: 'value',
          color: '#1890ff'
        });
        break;
      case 'pieChart':
        chart = new Pie(chartRef.current, {
          data,
          angleField: 'value',
          colorField: 'category'
        });
        break;
      case 'scatterChart':
        chart = new Scatter(chartRef.current, {
          data,
          xField: 'x',
          yField: 'y',
          color: '#1890ff'
        });
        break;
      case 'stackedAreaChart':
        chart = new Line(chartRef.current, {
          data,
          xField: 'category',
          yField: 'value',
          color: '#1890ff',
          point: {
            size: 3,
            shape: 'circle'
          },
          lineStyle: {
            lineWidth: 2
          }
        });
        break;
    }

    if (chart) {
      chart.render();
    }

    return () => {
      if (chart) {
        chart.destroy();
      }
    };
  }, [currentMode, tableData]);

  return (
    <div>
      <VisualizationControls currentMode={currentMode} onModeChange={setCurrentMode} onExport={handleExport} />
      {renderVisualization()}
    </div>
  );
};

// zeppelin-web-angular/src/app/visualizations/table/table-visualization.component.ts
/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ChangeDetectionStrategy, ChangeDetectorRef, Component, Inject, OnInit, ViewChild } from '@angular/core';

import { filter, maxBy, minBy, orderBy, sumBy } from 'lodash';
import { NzTableComponent, NzTableSortOrder } from 'ng-zorro-antd/table';
import { utils, writeFile, WorkSheet } from 'xlsx';

import { TableData, Visualization, VISUALIZATION } from '@zeppelin/visualization';

type ColType = 'string' | 'date' | 'number';
type AggregationType = 'count' | 'sum' | 'min' | 'max' | 'avg';

class FilterOption {
  sort: 'desc' | 'asc' | '' = '';
  type: ColType = 'string';
  visible = true;
  pinned?: string;
  term = '';
  width: string | '*' = '*';
  aggregation: AggregationType | null = null;
  aggregationValue: number | null = null;
}

function typeCoercion(value: string, type: ColType): string | number | Date {
  switch (type) {
    case 'number':
      const num = Number.parseFloat(value);
      return Number.isNaN(num) ? value : num;
    case 'date':
      const date = new Date(value);
      return Number.isNaN(date.valueOf()) ? value : date;
    default:
      return value;
  }
}

@Component({
  selector: 'zeppelin-visualization-table-visualization',
  templateUrl: './table-visualization.component.html',
  styleUrls: ['./table-visualization.component.less'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: false
})
export class TableVisualizationComponent implements OnInit {
  tableData?: TableData;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  rows: any[] = [];
  columns: string[] = [];
  colOptions = new Map<string, FilterOption>();
  types: ColType[] = ['string', 'number', 'date'];
  aggregations: AggregationType[] = ['count', 'sum', 'min', 'max', 'avg'];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  @ViewChild(NzTableComponent, { static: false }) nzTable!: NzTableComponent<any>;

  exportFile(type: 'csv' | 'xlsx', all = true) {
    const wb = utils.book_new();
    let ws: WorkSheet;
    if (all) {
      ws = utils.json_to_sheet(this.rows);
    } else {
      ws = utils.json_to_sheet([...this.nzTable.data]);
    }
    utils.book_append_sheet(wb, ws, 'Sheet1');
    writeFile(wb, `export.${type}`);
  }

  onChangeType(type: ColType, col: string) {
    this.getColOptionOrThrow(col).type = type;
    this.filterRows();
    this.aggregate();
  }

  onChangeAggregation(aggregation: AggregationType, col: string) {
    const opt = this.getColOptionOrThrow(col);
    opt.aggregation = opt.aggregation === aggregation ? null : aggregation;
    this.aggregate();
  }

  onSearch(): void {
    this.filterRows();
  }

  onSortChange(col: string, type: NzTableSortOrder): void {
    const opt = this.getColOptionOrThrow(col);
    this.colOptions.delete(col);
    if (type) {
      opt.sort = type === 'descend' ? 'desc' : 'asc';
    } else {
      opt.sort = '';
    }
    this.colOptions.set(col, opt);
    this.filterRows();
  }

  onTermChange(col: string, term: string) {
    this.getColOptionOrThrow(col).term = term;
  }

  getColOptionOrThrow(col: string): FilterOption {
    const opt = this.colOptions.get(col);
    if (!opt) {
      throw new Error('Column option should have been initialized');
    }
    return opt;
  }

  aggregate() {
    if (!this.tableData) {
      throw new Error('tableData is not defined');
    }
    const tableData = this.tableData;
    this.colOptions.forEach((opt, key) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const numValue = (row: any) => {
        const value = typeCoercion(row[key], opt.type);
        if (typeof value === 'number') {
          return value;
        }
        if (value instanceof Date) {
          return value.valueOf();
        }
        return value;
      };
      const getSum = () =>
        sumBy(tableData.rows, row => {
          const value = typeCoercion(row[key], 'number');
          return typeof value === 'number' ? value : 0;
        });

      switch (opt.aggregation) {
        case 'sum':
          opt.aggregationValue = getSum();
          break;
        case 'avg':
          opt.aggregationValue = getSum() / tableData.rows.length;
          break;
        case 'count':
          opt.aggregationValue = tableData.rows.length;
          break;
        case 'max':
          opt.aggregationValue = maxBy(tableData.rows, numValue)[key];
          break;
        case 'min':
          opt.aggregationValue = minBy(tableData.rows, numValue)[key];
          break;
        default:
          opt.aggregationValue = null;
      }
    });
  }

  filterRows() {
    if (!this.tableData) {
      throw new Error('tableData is not defined');
    }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const sortKeys: any[] = [];
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const sortTypes: any[] = [];
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const terms: any[] = [];
    this.colOptions.forEach((value, key) => {
      if (value.sort) {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        sortKeys.push((row: any) => typeCoercion(row[key], value.type));
        sortTypes.push(value.sort);
      }
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      terms.push((row: any) => String(row[key]).search(value.term) !== -1);
    });
    this.rows = filter(this.tableData.rows, row => terms.every(term => term(row)));
    this.rows = orderBy(this.rows, sortKeys, sortTypes);
    this.cdr.markForCheck();
  }

  constructor(
    @Inject(VISUALIZATION) public visualization: Visualization,
    private cdr: ChangeDetectorRef
  ) {}

  ngOnInit() {}

  render() {
    this.tableData = this.visualization.transformed;
    this.columns = this.tableData!.columns;
    this.rows = [...this.tableData!.rows];
    this.columns.forEach(col => {
      this.colOptions.set(col, new FilterOption());
    });
    this.filterRows();
  }
}

<!--
~ Licensed under the Apache License, Version 2.0 (the "License");
~ you may not use this file except in compliance with the License.
~ You may obtain a copy of the License at
~     http://www.apache.org/licenses/LICENSE-2.0
~ Unless required by applicable law or agreed to in writing, software
~ distributed under the License is distributed on an "AS IS" BASIS,
~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
~ See the License for the specific language governing permissions and
~ limitations under the License.
-->

<button class="export-dropdown" nz-button nz-dropdown nzSize="small" [nzDropdownMenu]="menu">
  <span>Export</span>
  <i nz-icon nzType="down"></i>
</button>
<nz-dropdown-menu #menu="nzDropdownMenu">
  <ul nz-menu>
    <li nz-menu-item>
      <a (click)="exportFile('csv')">Export all data as csv</a>
    </li>
    <li nz-menu-item>
      <a (click)="exportFile('xlsx')">Export all data as excel</a>
    </li>
    <li nz-menu-item>
      <a (click)="exportFile('csv', false)">Export visible data as csv</a>
    </li>
    <li nz-menu-item>
      <a (click)="exportFile('xlsx', false)">Export visible data as excel</a>
    </li>
    <li nz-menu-divider></li>
    <li nz-menu-item>
      <a (click)="copyToClipboard('tsv')">Copy all data as TSV</a>
    </li>
    <li nz-menu-item>
      <a (click)="copyToClipboard('csv')">Copy all data as CSV</a>
    </li>
    <li nz-menu-item>
      <a (click)="copyToClipboard('tsv', false)">Copy visible data as TSV</a>
    </li>
    <li nz-menu-item>
      <a (click)="copyToClipboard('csv', false)">Copy visible data as CSV</a>
    </li>
  </ul>
</nz-dropdown-menu>
<nz-table
  #table
  nzSize="small"
  nzShowSizeChanger
  [nzScroll]="{ x: '1300px' }"
  [nzData]="rows"
  [nzFooter]="aggregatesFooter"
>
  <thead>
    <tr>
      @for (col of columns; track col) {
        <th nzWidth="200px" nzShowSort nzCustomFilter (nzSortOrderChange)="onSortChange(col, $event)">
          {{ col }}
          <i
            #dropdown="nzDropdown"
            nz-icon
            nzType="down"
            nzTrigger="click"
            nzPlacement="bottomRight"
            [nzClickHide]="false"
            [nzDropdownMenu]="filterMenu"
            nzTableFilter
            [nzRotate]="dropdown.nzVisible ? 180 : 0"
            class="ant-table-filter-icon filter-icon"
            [class.ant-table-filter-open]="dropdown.nzVisible"
            nz-dropdown
          ></i>
          <nz-dropdown-menu #filterMenu="nzDropdownMenu">
            <ul nz-menu class="th-dropdown">
              <li nz-menu-group class="search-bar">
                <nz-input-group nzSearch [nzAddOnAfter]="suffixIconButton">
                  <input
                    type="text"
                    nz-input
                    placeholder="Search..."
                    (blur)="onSearch()"
                    (keydown.enter)="onSearch()"
                    [ngModel]="getColOptionOrThrow(col).term"
                    (ngModelChange)="onTermChange(col, $event)"
                  />
                </nz-input-group>
                <ng-template #suffixIconButton>
                  <button nz-button nzSearch nzType="primary" (click)="onSearch()">
                    <i nz-icon nzType="search" nzTheme="outline"></i>
                  </button>
                </ng-template>
              </li>
              <li nz-menu-divider></li>
              <li nz-menu-group>
                <span title>Type</span>
                <ul>
                  @for (type of types; track type) {
                    <li
                      nz-menu-item
                      [nzSelected]="getColOptionOrThrow(col).type === type"
                      (click)="onChangeType(type, col)"
                    >
                      {{ type | titlecase }}
                    </li>
                  }
                </ul>
              </li>
              <li nz-menu-divider></li>
              <li nz-menu-group>
                <span title>Aggregation</span>
                <ul>
                  @for (aggregation of aggregations; track aggregation) {
                    <li
                      nz-menu-item
                      [nzSelected]="getColOptionOrThrow(col).aggregation === aggregation"
                      (click)="onChangeAggregation(aggregation, col)"
                    >
                      {{ aggregation | titlecase }}
                    </li>
                  }
                </ul>
              </li>
            </ul>
          </nz-dropdown-menu>
        </th>
      }
    </tr>
  </thead>
  <tbody>
    @for (data of table.data; track data) {
      <tr>
        @for (col of columns; track col) {
          <td>{{ data[col] }}</td>
        }
      </tr>
    }
  </tbody>
</nz-table>
<ng-template #aggregatesFooter>
  <div class="aggregation-wrap">
    @for (col of columns; track col) {
      <span>
        @if (getColOptionOrThrow(col).aggregation; as aggregation) {
          <span class="aggregation-item">
            {{ aggregation }}(
            <strong>{{ col }}</strong>
            ):
            <span>{{ getColOptionOrThrow(col).aggregationValue }}</span>
          </span>
        }
      </span>
    }
  </div>
</ng-template>
